spring:
  application:
    name: codegen-blueprint

codegen:
  profiles:
    springboot-maven-java:
      template-base-path: springboot/maven/java/

      ordered-artifact-keys:
        - build-config
        - build-tool-metadata
        - ignore-rules
        - app-config
        - main-source-entrypoint
        - test-source-entrypoint
        - project-documentation

      artifacts:
        build-config:
          templates:
            - template: pom.xml.ftl
              output-path: pom.xml

        build-tool-metadata:
          templates:
            - template: maven-wrapper.properties.ftl
              output-path: .mvn/wrapper/maven-wrapper.properties

        ignore-rules:
          templates:
            - template: gitignore.ftl
              output-path: .gitignore

        app-config:
          templates:
            - template: application.yml.ftl
              output-path: src/main/resources/application.yml

        main-source-entrypoint:
          templates:
            - template: MainClass.java.ftl
              output-path: src/main/java

        test-source-entrypoint:
          templates:
            - template: MainClassTests.java.ftl
              output-path: src/test/java

        project-documentation:
          templates:
            - template: README.md.ftl
              output-path: README.md

templating:
  encoding: UTF-8
  handler: RETHROW
  template-path: /templates
  cache-enabled: true
  cache-update-delay-ms: 60000
