spring:
  application:
    name: codegen-springboot-initializr


codegen:
  profiles:
    springboot-maven-java:
      template-base-path: springboot/maven/java
      ordered-artifact-keys: [ pom, gitignore, application-yaml, readme ]  # execution order
      artifacts:
        pom:
          template: pom.xml.ftl
          output-path: pom.xml
        gitignore:
          template: .gitignore.ftl
          output-path: .gitignore
        application-yaml:
          template: application.yml.ftl
          output-path: src/main/resources/application.yml
        readme:
          template: README.md.ftl
          output-path: README.md

templating:
  encoding: UTF-8
  handler: RETHROW
  template-path: /templates
  cache-enabled: true
  cache-update-delay-ms: 60000


freemarker:
  encoding: UTF-8
  template-exception-handler: RETHROW_HANDLER
  template-path: /templates

maven:
  source-folder:
    src-main-java: src/main/java
    src-main-resources: src/main/resources
    src-test-java: src/test/java
    src-test-resources: src/test/resources
    src-gen-java: src/gen/java